import type { Metadata } from "next";
import { Handjet, Rakkas } from "next/font/google";
import "./globals.css";

const rakkas = Rakkas({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-rakkas",
});

const handjet = Handjet({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-handjet",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(rakkas.variable);
  return (
    <html
      dir="rtl"
      lang="ar"
      className={`${rakkas.variable} ${handjet.variable} font-rakkas`}
    >
      <body>{children}</body>
    </html>
  );
}
